name: Resolve Retention Days
description: Resolves artifact retention days based on build type and defaults.json

inputs:
  buildType:
    description: The resolved build type (preview, release_candidate, release)
    required: true
  retentionDaysReleaseOverride:
    description: Override for release retention days
    required: false
  retentionDaysRcOverride:
    description: Override for release candidate retention days
    required: false
  retentionDaysPreviewOverride:
    description: Override for preview retention days
    required: false
  defaultsFileOverride:
    description: 'Optional path (in your workspace) to a custom defaults.json'
    required: false

outputs:
  retentionDays:
    description: Resolved retention days
    value: ${{ steps.set.outputs.retentionDays }}

runs:
  using: "composite"
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/resolve-retention-days.sh"

    - id: set
      shell: bash
      env:
        DEFAULTS_FILE_OVERRIDE: ${{ inputs.defaultsFileOverride }}
        RETENTION_DAYS_RELEASE_OVERRIDE: ${{ inputs.retentionDaysReleaseOverride }}
        RETENTION_DAYS_RC_OVERRIDE: ${{ inputs.retentionDaysRcOverride }}
        RETENTION_DAYS_PREVIEW_OVERRIDE: ${{ inputs.retentionDaysPreviewOverride }}
      run: |
        bash "${{ github.action_path }}/resolve-retention-days.sh" "${{ inputs.buildType }}"
