name: Resolve Test Config
description: Resolves Unity test config values from overrides or defaults.json
author: Avalin

inputs:
  unityVersionOverride:
    description: Override for Unity version
    required: false
  useGitLfsOverride:
    description: Override for Git LFS usage
    required: false
  editModePathOverride:
    description: Override for EditMode test path
    required: false
  playModePathOverride:
    description: Override for PlayMode test path
    required: false
  quietModeOverride:
    description: Override for Quiet Mode
    required: false
  defaultsFileOverride:
    description: 'Optional path (in your workspace) to a custom defaults.json'
    required: false

outputs:
  unityVersion:
    description: Resolved Unity version
    value: ${{ steps.set.outputs.unityVersion }}
  useGitLfs:
    description: Resolved Git LFS usage
    value: ${{ steps.set.outputs.useGitLfs }}
  editModePath:
    description: Resolved EditMode path
    value: ${{ steps.set.outputs.editModePath }}
  playModePath:
    description: Resolved PlayMode path
    value: ${{ steps.set.outputs.playModePath }}
  quietMode:
    description: Resolved Quiet Mode
    value: ${{ steps.set.outputs.quietMode }}

runs:
  using: "composite"
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/resolve-test-config.sh"

    - id: set
      shell: bash
      env:
        DEFAULTS_FILE_OVERRIDE: ${{ inputs.defaultsFileOverride }}
        UNITY_VERSION_OVERRIDE: ${{ inputs.unityVersionOverride }}
        USE_GIT_LFS_OVERRIDE: ${{ inputs.useGitLfsOverride }}
        EDIT_MODE_PATH_OVERRIDE: ${{ inputs.editModePathOverride }}
        PLAY_MODE_PATH_OVERRIDE: ${{ inputs.playModePathOverride }}
        QUIET_MODE_OVERRIDE: ${{ inputs.quietModeOverride }}
      run: |
        bash "${{ github.action_path }}/resolve-test-config.sh"
