name: 💬 Format Notification Messages

description: |
  Formats final notification messages for Slack and Discord from a prepared message block.

inputs:
  title:
    description: "Notification title"
    required: true
  status:
    description: "Notification status (success, failure, etc.)"
    required: true
  message:
    description: "Main body message"
    required: true
  runUrl:
    description: "GitHub Actions run URL"
    required: true
  releaseUrl:
    description: "GitHub Release URL"
    required: true
  deployResultsPath:
    description: "Path to deployment result JSON files"
    required: true

outputs:
  title:
    description: "Final title"
    value: ${{ steps.format.outputs.title }}
  status:
    description: "Final status"
    value: ${{ steps.format.outputs.status }}
  message:
    description: "Formatted message body"
    value: ${{ steps.format.outputs.message }}
  slackMessage:
    description: "Slack-formatted message"
    value: ${{ steps.format.outputs.slackMessage }}
  discordMessage:
    description: "Discord-formatted message"
    value: ${{ steps.format.outputs.discordMessage }}

runs:
  using: "composite"
  steps:
    - name: 💬 Format Final Notification Messages
      id: format
      shell: bash
      run: |
        cd ${{ github.workspace }}
        chmod +x ${{ github.action_path }}/format-slack.sh
        chmod +x ${{ github.action_path }}/format-discord.sh

        FINAL_MESSAGE=$(bash ${{ github.action_path }}/format-slack.sh "${{ inputs.message }}" "${{ inputs.runUrl }}" "${{ inputs.releaseUrl }}" "${{ inputs.deployResultsPath }}")
        SLACK_MESSAGE="$FINAL_MESSAGE"
        DISCORD_MESSAGE=$(bash ${{ github.action_path }}/format-discord.sh "${{ inputs.message }}" "${{ inputs.runUrl }}" "${{ inputs.releaseUrl }}" "${{ inputs.deployResultsPath }}")

        echo "title=${{ inputs.title }}" >> "$GITHUB_OUTPUT"
        echo "status=${{ inputs.status }}" >> "$GITHUB_OUTPUT"

        echo "message<<EOF" >> "$GITHUB_OUTPUT"
        echo "$FINAL_MESSAGE" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        echo "slackMessage<<EOF" >> "$GITHUB_OUTPUT"
        echo "$SLACK_MESSAGE" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        echo "discordMessage<<EOF" >> "$GITHUB_OUTPUT"
        echo "$DISCORD_MESSAGE" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
