name: Resolve Unity Version
description: Resolves Unity test config values from overrides or defaults.json

inputs:
  unityVersionOverride:
    description: Override for Unity version
    required: false

outputs:
  unityVersion:
    description: Resolved Unity version
    value: ${{ steps.set.outputs.unityVersion }}

runs:
  using: "composite"
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/resolve-Unity-version.sh"

    - id: set
      shell: bash
      env:
        UNITY_VERSION_OVERRIDE: ${{ inputs.unityVersionOverride }}
      run: |
        bash "${{ github.action_path }}/resolve-Unity-version.sh"