name: 🏷️ Build Version Generator

on:
  workflow_call:
    inputs:
      buildType:
        description: "Build type (preview or release)"
        required: true
        type: string
    outputs:
      version:
        description: "The generated build version"
        value: ${{ jobs.determine.outputs.version }}

jobs:
  determine:
    name: 🏷️ Generate Build Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Version
        id: get_version
        shell: bash
        run: |
          REF="${GITHUB_REF}"
          EVENT="${GITHUB_EVENT_NAME}"

          if [[ "$REF" =~ ^refs/pull/([0-9]+)/merge$ ]]; then
            # --- Pull Request build
            PR_NUMBER=$(printf "%04d" "${BASH_REMATCH[1]}")
            VERSION="PR-${PR_NUMBER}"

          elif [[ "$REF" =~ ^refs/tags/(v?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?)$ ]]; then
            # --- Tag build (accepts both v1.2.3 and 1.2.3)
            VERSION="${BASH_REMATCH[1]}"

          elif [[ "$REF" =~ ^refs/heads/(.+)$ ]]; then
            BRANCH_NAME=$(echo "${BASH_REMATCH[1]}" | tr '/' '-')
            if [[ "$EVENT" == "workflow_dispatch" ]]; then
              VERSION="manual-${BRANCH_NAME}"
            else
              VERSION="${BRANCH_NAME}"
            fi
          else
            # Fallback for weird cases like detached HEAD
            SHORT_SHA=$(git rev-parse --short HEAD)
            VERSION="commit-${SHORT_SHA}"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "🏷️ Determined version: $VERSION"