name: ⏳ CI/CD Prerequisites

on:
  workflow_call:
    inputs:
      excludesUnityTests:
        description: "Whether unity tests are excluded"
        type: string
        required: true
      deployTargets:
        description: "JSON array of deploy targets (e.g. ['itch.io','appcenter','firebase','s3','gh-pages'])"
        type: string
        default: '[]'
        required: false
      artifactSource:
        description: "Where we get our artifacts from"
        type: string
        default: 'build'
        required: false
    outputs:
      validDeployTargets:
        description: "JSON array of filtered and validated deploy targets"
        value: ${{ jobs.validate-deploy-targets.outputs.validTargets }}
      requiresCombinedArtifact:
        description: "Whether any deploy target requires a combined artifact"
        value: ${{ jobs.analyze-artifact-strategy.outputs.requiresCombined || 'true' }}
      skipPerPlatformArtifacts:
        description: "Whether per-platform artifacts can be skipped"
        value: ${{ jobs.analyze-artifact-strategy.outputs.skipPerPlatform || 'true' }}

jobs:
  validate-vars:
    name: Validate GitHub Variables
    uses: avalin/unity-ci-templates/.github/workflows/validate-github-vars.yml@main
    with:
      requiredVars: |
        [
          "COMBINE_ARTIFACTS",
          "DEPLOY_TARGETS",
          "EXCLUDE_UNITY_TESTS",
          "PROJECT_NAME",
          "RETENTION_DAYS_PREVIEW",
          "RETENTION_DAYS_RELEASE",
          "TARGET_PLATFORMS_PREVIEW",
          "TARGET_PLATFORMS_RELEASE"
        ]

  validate-deploy-targets:
    uses: ./.github/workflows/validate-deploy-targets.yml
    with:
      deployTargets: ${{ inputs.deployTargets }}

  analyze-artifact-strategy:
    name: 🔍 Analyze Artifact Strategy
    needs: validate-deploy-targets
    if: needs.validate-deploy-targets.outputs.skipAnalysis != 'true'
    uses: ./.github/workflows/analyze-artifact-strategy.yml
    with:
      artifactSource: ${{ inputs.artifactSource }}
      deployTargets: ${{ needs.validate-deploy-targets.outputs.validTargets }}

  upload-license:
    name: 📥️ Upload Unity License
    if: ${{ inputs.excludesUnityTests == 'false' }}
    uses: ./.github/workflows/unity-license-uploader.yml
    secrets: inherit