name: ▶️ Trigger Full Pipeline

on:
  # Allow manual dispatch with a buildType input
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: 'preview' for manual/dev builds, 'release_candidate' for staging (e.g., v1.2.3-rc.1), 'release' for production (e.g., v1.2.3)"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release_candidate
          - release
      version:
        description: Optional version override
        type: string
        required: false
  # Automatically run tests & builds on certain branches or PR changes
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    types: [ready_for_review, synchronize, reopened]
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-metadata:
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      buildType: ${{ inputs.buildType }}
      version: ${{ inputs.version }}
  
  trigger-ci:
    name: Trigger CI/CD Pipeline
    needs: prepare-metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Trigger downstream pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_PAT }}
        run: |
          gh workflow run ci-cd-full.yml \
            --ref "${{ github.ref }}" \
            --field buildType="${{ needs.prepare-metadata.outputs.buildType }}" \
            --field version="${{ needs.prepare-metadata.outputs.version }}" \
            --field validDeployTargets="$(printf '%s' '${{ needs.prepare-metadata.outputs.validDeployTargets }}')" \
            --field requiresCombined="${{ needs.prepare-metadata.outputs.requiresCombined }}" \
            --field skipPerPlatform="${{ needs.prepare-metadata.outputs.skipPerPlatform }}"
