name: 🚀 Full CI/CD Pipeline

on:
  # Allow manual dispatch with a buildType input
  workflow_dispatch:
    inputs:
      buildType:
        description: "preview = manual/development build | release = only via Git tag (v1.2.3)"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
      targetPlatforms:
        description: "JSON array of platforms to build"
        type: string
        default: '["Android","WebGL","StandaloneLinux64","StandaloneWindows","StandaloneWindows64","StandaloneOSX","iOS"]'
        required: false
  # Automatically run tests & builds on certain branches or PR changes
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    types: [ready_for_review, synchronize, reopened]
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  # ─────────────────────────────────────────────────────────────────────────────
  # 1. Run Tests
  # ─────────────────────────────────────────────────────────────────────────────
  run-tests:
    name: Run Tests
    uses: avalin/unity-ci-templates/.github/workflows/step-1-test.yml@main
    with:
      unityVersion: ${{ vars.UNITY_VERSION }}
      licenseArtifactName: ${{ vars.LICENSE_ARTIFACT_NAME }}
      useGitLfs: ${{ vars.USE_GIT_LFS }}
      editModePath: ${{ vars.UNITY_TESTS_EDITMODE_PATH }}
      playModePath: ${{ vars.UNITY_TESTS_PLAYMODE_PATH }}
      timeoutMinutes: ${{ fromJson(vars.TIMEOUT_TESTS_IN_MINUTES) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  # ─────────────────────────────────────────────────────────────────────────────
  # 2. Build
  # ─────────────────────────────────────────────────────────────────────────────
  build:
    name: Build
    needs: [ run-tests ]
    # Build if ANY of these conditions are met:
    # - The event is a pull_request, ready for review.
    # - The event is a workflow_dispatch (manual trigger).
    # - The event is a push and the ref starts with 'refs/tags/' (a tag push for release).
    if: >
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    uses: avalin/unity-ci-templates/.github/workflows/step-2-build.yml@main
    with:
      # If the event is a push with a tag, force buildType to "release"; otherwise, use the input.
      projectName: ${{ vars.PROJECT_NAME }}
      buildType: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && 'release' || github.event.inputs.buildType }}
      targetPlatforms: ${{ vars.TARGET_PLATFORMS }}
      timeoutMinutes: ${{ fromJson(vars.TIMEOUT_BUILD_IN_MINUTES) }}
      retentionDays: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && fromJson(vars.RETENTION_DAYS_RELEASE) || fromJson(vars.RETENTION_DAYS_PREVIEW) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  # ─────────────────────────────────────────────────────────────────────────────
  # 3. Release
  # ─────────────────────────────────────────────────────────────────────────────
  release:
    name: Release
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    uses: avalin/unity-ci-templates/.github/workflows/step-3-release.yml@main
    with:
      buildType: release
      version: ${{ github.ref_name }}
      projectName: ${{ vars.PROJECT_NAME }}
      targetPlatforms: ${{ vars.TARGET_PLATFORMS }}
    secrets: inherit
