name: ⏳ CI/CD Prerequisites

on:
  workflow_call:
    inputs:
      excludesUnityTests:
        description: "Whether unity tests are excluded"
        type: string
        required: true
      deployTargets:
        description: "JSON array of deploy targets (e.g. ['itch.io','appcenter','firebase','s3','gh-pages'])"
        type: string
        default: '[]'
        required: false
    outputs:
      requiresCombinedArtifact:
        description: "Whether any deploy target requires a combined artifact"
        value: ${{ jobs.determine-combined-artifact-requirement.outputs.requiresCombinedArtifact }}

jobs:
  validate-vars:
    name: Validate GitHub Variables
    uses: avalin/unity-ci-templates/.github/workflows/validate-github-vars.yml@main
    with:
      requiredVars: |
        [
          "COMBINE_ARTIFACTS",
          "DEPLOY_TARGETS",
          "EXCLUDE_UNITY_TESTS",
          "PROJECT_NAME",
          "RETENTION_DAYS_PREVIEW",
          "RETENTION_DAYS_RELEASE",
          "TARGET_PLATFORMS_PREVIEW",
          "TARGET_PLATFORMS_RELEASE"
        ]

  upload-license:
    name: 📥️ Upload Unity License
    if: ${{ inputs.excludesUnityTests == 'false' }}
    uses: ./.github/workflows/unity-license-uploader.yml
    secrets: inherit

  determine-combined-artifact-requirement:
    name: 🔍 Determine Combined Artifact Requirement
    uses: ./.github/workflows/determine-artifact-requirements.yml
    with:
      deployTargets: ${{ inputs.deployTargets }}
      