name: 🚀 Full CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Choose build type"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  # Step 1: Run Tests
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/step-1-tests.yml
    with:
      unityVersion: '2022.3.60f1'
      licenseArtifactName: 'unity-license'
      useGitLfs: 'true'
      editModePath: 'Assets/Tests/Editor'
      playModePath: 'Assets/Tests/PlayMode'
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  # Step 2: Build
  build:
    name: Build
    needs: run-tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Display Build Info (Mock)
        run: |
          echo "Build Type: ${{ github.event.inputs.buildType || 'N/A' }}"
          echo "Triggered by: ${{ github.event_name }}"
          echo "This is a mock build step. Replace with actual build commands when ready."