name: 🚀 Full CI/CD Pipeline

on:
  # Allow manual dispatch with a buildType input
  workflow_dispatch:
    inputs:
      targetPlatforms:
        description: "JSON array of platforms to build"
        type: string
        default: '["Android","WebGL","StandaloneLinux64","StandaloneWindows","StandaloneWindows64","StandaloneOSX","iOS"]'
        required: false
      buildType:
        description: "Choose build type"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release
  
  # Automatically run tests & builds on certain branches or PR changes
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  # ─────────────────────────────────────────────────────────────────────────────
  # 1. Run Tests
  # ─────────────────────────────────────────────────────────────────────────────
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/step-1-test.yml
    with:
      unityVersion: '2022.3.60f1'
      licenseArtifactName: 'unity-license'
      useGitLfs: 'true'
      editModePath: 'Assets/Tests/Editor'
      playModePath: 'Assets/Tests/PlayMode'
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  # ─────────────────────────────────────────────────────────────────────────────
  # 2. Build
  # ─────────────────────────────────────────────────────────────────────────────
  build:
    name: Build
    needs: [ run-tests ]
    # Only build if:
    # - We have a pull request
    # - We have manual dispatch (either preview or release)
    # - We are pushing to "main"
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch') ||
      github.ref == 'refs/heads/main'
    uses: ./.github/workflows/step-2-build.yml
    with:
      targetPlatforms: '["Android","iOS"]'
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}