name: ⏳ Prepare Metadata

on:
  workflow_call:
    inputs:
      deployTargets:
        type: string
        required: true
      buildType:
        type: string
        required: false
      skipTests:
        type: string
        required: false
      skipBuild:
        type: string
        required: false
        default: 'false'
      testsOnly:
        type: string
        required: false
      version:
        type: string
        required: false
    outputs:
      buildType:
        value: ${{ jobs.metadata.outputs.buildType }}
      triggeredBy:
        value: ${{ jobs.metadata.outputs.triggeredBy }}
      testsOnly:
        value: ${{ jobs.metadata.outputs.testsOnly }}
      skipTests:
        value: ${{ jobs.metadata.outputs.skipTests }}
      version:
        value: ${{ jobs.metadata.outputs.version }}
      validDeployTargets:
        value: ${{ jobs.metadata.outputs.validDeployTargets }}
      requiresCombined:
        value: ${{ jobs.metadata.outputs.requiresCombined }}
      skipPerPlatform:
        value: ${{ jobs.metadata.outputs.skipPerPlatform }}

jobs:
  detect_tests_only:
    name: Detect Tests-Only Run
    runs-on: ubuntu-latest
    outputs:
      testsOnly: ${{ steps.detect.outputs.testsOnly }}
    steps:
      - id: detect
        run: |
          IS_TESTS_ONLY="false"

          # Manual flag (from dispatch input)
          if [[ "${{ inputs.testsOnly }}" == "true" ]]; then
            IS_TESTS_ONLY="true"
          fi

          # Auto-detect based on event
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TYPE="${{ github.event.action }}"
            if [[ "$TYPE" == "ready_for_review" || "$TYPE" == "synchronize" || "$TYPE" == "reopened" ]]; then
              IS_TESTS_ONLY="true"
            fi
          fi

          echo "testsOnly=$IS_TESTS_ONLY" >> "$GITHUB_OUTPUT"

  detect_skip_tests:
    name: Detect Skip Tests
    needs: detect_tests_only
    runs-on: ubuntu-latest
    env:
      TESTS_ONLY: ${{ needs.detect_tests_only.outputs.testsOnly }}
    outputs:
      skipTests: ${{ steps.detect.outputs.skipTests }}
    steps:
      - id: detect
        run: |
          # Default to false
          SKIP_TESTS=false

          # Check vars.EXCLUDE_UNITY_TESTS unless TESTS_ONLY
          if [ "$TESTS_ONLY" = "true" ]; then
            SKIP_TESTS="false"
          elif [[ "${{ vars.EXCLUDE_UNITY_TESTS }}" == "true" ]]; then
            SKIP_TESTS=true
          fi

          # Check commit message if this is a push event
          if [[ "$GITHUB_EVENT_NAME" == "push" && -f "$GITHUB_EVENT_PATH" ]]; then
            COMMIT_MSG=$(jq -r .head_commit.message < "$GITHUB_EVENT_PATH")
            if [[ "$COMMIT_MSG" == *"[skip tests]"* ]]; then
              SKIP_TESTS=true
            fi
          fi

          echo "skipTests=$SKIP_TESTS" >> "$GITHUB_OUTPUT"

  resolve_trigger:
    name: Resolve Github Event Trigger
    runs-on: ubuntu-latest
    outputs:
      triggeredBy: ${{ steps.event.outputs.triggeredBy }}
    steps:
      - id: event
        run: echo "triggeredBy=$GITHUB_EVENT_NAME" >> "$GITHUB_OUTPUT"

  resolve_build_type:
    name: Resolve Build Type (Preview, RC, Release)
    needs: detect_tests_only
    runs-on: ubuntu-latest
    env:
      TESTS_ONLY: ${{ needs.detect_tests_only.outputs.testsOnly }}
    outputs:
      buildType: ${{ steps.set.outputs.buildType }}
    steps:
      - id: set
        run: |
          if [ "$TESTS_ONLY" = "true" ]; then
            BUILD_TYPE="preview"
          elif [ "${{ github.event_name }}" = "push" ]; then
            BUILD_TYPE="release"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            BUILD_TYPE="${{ inputs.buildType || 'preview' }}"
          else
            BUILD_TYPE="${{ inputs.buildType || 'preview' }}"
          fi
          echo "buildType=$BUILD_TYPE" >> $GITHUB_OUTPUT

  resolve_retention_days:
    name: Resolve Retention Days
    needs:
      - resolve_build_type
    runs-on: ubuntu-latest
    outputs:
      retentionDays: ${{ steps.set.outputs.retentionDays }}
    steps:
      - id: set
        run: |
          BUILD_TYPE="${{ needs.resolve_build_type.outputs.buildType }}"
          DEFAULT_RELEASE_DAYS=30
          DEFAULT_PREVIEW_DAYS=7

          if [[ "$BUILD_TYPE" == "release" ]]; then
            RETENTION_DAYS="${{ vars.RETENTION_DAYS_RELEASE || '' }}"
            RETENTION_DAYS="${RETENTION_DAYS:-$DEFAULT_RELEASE_DAYS}"
          else
            RETENTION_DAYS="${{ vars.RETENTION_DAYS_PREVIEW || '' }}"
            RETENTION_DAYS="${RETENTION_DAYS:-$DEFAULT_PREVIEW_DAYS}"
          fi

          echo "✅ Retention days resolved to: $RETENTION_DAYS"
          echo "retentionDays=$RETENTION_DAYS" >> "$GITHUB_OUTPUT"

  version:
    name: Create versioning
    needs: 
      - resolve_build_type
      - detect_tests_only
    if: needs.detect_tests_only.outputs.testsOnly == 'false' && inputs.skipBuild == 'false'
    uses: ./.github/workflows/version-resolver.yml
    with:
      buildType: ${{ needs.resolve_build_type.outputs.buildType }}
      version: ${{ inputs.version }}

  validate_deploy_targets:
    name: Validate Deploy Targets    
    needs: detect_tests_only
    if: needs.detect_tests_only.outputs.testsOnly == 'false'
    uses: ./.github/workflows/validate-deploy-targets.yml
    with:
      deployTargets: ${{ inputs.deployTargets }}

  analyze_artifact_strategy:
    name: Analyze Artifact Strategy
    needs: validate_deploy_targets
    if: needs.validate_deploy_targets.outputs.skipAnalysis != 'true'
    uses: ./.github/workflows/analyze-artifact-strategy.yml
    with:
      artifactSource: build
      deployTargets: ${{ needs.validate_deploy_targets.outputs.validTargets }}

  metadata:
    name: Summarize Metadata
    runs-on: ubuntu-latest
    if: always()
    needs:
      - detect_skip_tests
      - detect_tests_only
      - resolve_trigger
      - resolve_build_type
      - resolve_retention_days
      - version
      - validate_deploy_targets
      - analyze_artifact_strategy
    outputs:
      version: ${{ needs.version.outputs.version || (inputs.version != '' && inputs.version) || 'N/A' }}
      buildType: ${{ needs.resolve_build_type.outputs.buildType }}
      skipTests: ${{ needs.detect_skip_tests.outputs.skipTests }}
      testsOnly: ${{ needs.detect_tests_only.outputs.testsOnly }}
      triggeredBy: ${{ needs.resolve_trigger.outputs.triggeredBy }}
      retentionDays: ${{ needs.resolve_retention_days.outputs.retentionDays }}
      validDeployTargets: ${{ needs.validate_deploy_targets.outputs.validTargets || '[]' }}
      requiresCombined: ${{ needs.analyze_artifact_strategy.outputs.requiresCombined || false }}
      skipPerPlatform: ${{ needs.analyze_artifact_strategy.outputs.skipPerPlatform || false }}
    steps:
      - name: Summarize
        run: |
          DEPLOY_TARGETS=$(echo '${{ needs.validate_deploy_targets.outputs.validTargets }}' | jq -c '.')
          # If after jq we get an empty or blank result, replace it with []
          if [[ -z "$DEPLOY_TARGETS" || "$DEPLOY_TARGETS" == 'null' ]]; then
            DEPLOY_TARGETS='[]'
          fi

          echo "## ⏳ Build Metadata Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Key                          | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|------------------------------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Version                      | ${{ needs.version.outputs.version || (inputs.version != '' && inputs.version) || 'N/A' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build Type                   | ${{ needs.resolve_build_type.outputs.buildType }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Skip Tests                   | ${{ needs.detect_skip_tests.outputs.skipTests }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Tests Only                   | ${{ needs.detect_tests_only.outputs.testsOnly }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Triggered by                 | ${{ needs.resolve_trigger.outputs.triggeredBy }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Retention Days               | ${{ needs.resolve_retention_days.outputs.retentionDays }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Deploy Targets               | \`$DEPLOY_TARGETS\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Requires Combined Artifacts  | ${{ needs.analyze_artifact_strategy.outputs.requiresCombined || false }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Skip Per-Platform Artifacts  | ${{ needs.analyze_artifact_strategy.outputs.skipPerPlatform || false }} |" >> $GITHUB_STEP_SUMMARY