name: 🧮 Resolve Build Targets

on:
  workflow_call:
    inputs:
      buildTargets:
        type: string
        required: false
      buildType:
        type: string
        required: true
    outputs:
      validatedBuildTargets:
        value: ${{ jobs.resolve.outputs.validatedBuildTargets }}

jobs:
  resolve:
    name: Resolve Build Targets
    runs-on: ubuntu-latest
    outputs:
      validatedBuildTargets: ${{ steps.set.outputs.validatedBuildTargets }}
    steps:
      - name: Checkout Repository (for local config)
        uses: actions/checkout@v4

      - id: set
        run: |
          INPUT_BUILD_TARGETS='${{ inputs.buildTargets || '[]' }}'
          BUILD_TYPE='${{ inputs.buildType }}'
          CONFIG_FILE=".github/config/build-targets.json"
          FALLBACK_URL="https://raw.githubusercontent.com/avalin/unity-ci-templates/main/.github/config/build-targets.json"

          echo "🔍 Checking for local config file..."
          if [ -f "$CONFIG_FILE" ]; then
            echo "✅ Found local config: $CONFIG_FILE"
          else
            echo "⚠️ Not found. Downloading fallback from: $FALLBACK_URL"
            mkdir -p "$(dirname "$CONFIG_FILE")"
            curl -sSL "$FALLBACK_URL" -o "$CONFIG_FILE"
          fi

          # Convert buildType to numeric priority
          type_weight() {
            case "$1" in
              preview) echo 1 ;;
              release_candidate) echo 2 ;;
              release) echo 3 ;;
              *) echo 0 ;;
            esac
          }

          BUILD_WEIGHT=$(type_weight "$BUILD_TYPE")
          VALIDATED="[]"

          for TARGET in $(echo "$INPUT_BUILD_TARGETS" | jq -r '.[]'); do
            if jq -e --arg p "$TARGET" '.[$p]' "$CONFIG_FILE" >/dev/null; then
              MIN_TYPE=$(jq -r --arg p "$TARGET" '.[$p].minimumBuildType' "$CONFIG_FILE")
              MIN_WEIGHT=$(type_weight "$MIN_TYPE")

              if [ "$BUILD_WEIGHT" -ge "$MIN_WEIGHT" ]; then
                VALIDATED=$(echo "$VALIDATED" | jq --arg p "$TARGET" '. + [$p]')
              else
                echo "⚠️ Skipping $TARGET — needs $MIN_TYPE"
              fi
            else
              echo "⚠️ Unknown build target $TARGET — skipping"
            fi
          done

          echo "✅ Validated build targets: $VALIDATED"
          echo "validatedBuildTargets<<EOF" >> "$GITHUB_OUTPUT"
          echo "$VALIDATED" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"