name: 🧪 Test Reusable Unity Test Runner

on:
  workflow_dispatch:

jobs:
  activate-unity:
    name: 🔐 Activate Unity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload Unity License File
        run: |
          LICENSE_PATH="$HOME/.local/share/unity3d/Unity/Unity_lic.ulf"
          if [ -f "$LICENSE_PATH" ]; then
            echo "✅ License file found, uploading..."
            mkdir -p license
            cp "$LICENSE_PATH" license/
          else
            echo "❌ License file not found"
            exit 1
          fi

      - name: Upload License Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-license
          path: license/Unity_lic.ulf

  run-editmode:
    needs: activate-unity
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode
    secrets: inherit

  run-playmode:
    needs: activate-unity
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
    secrets: inherit