name: 🔍 Step 0 - Static Analysis

on:
  workflow_call:

jobs:
  analyze:
    name: Run dotnet format (if .sln exists)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Check for .sln file
        id: sln_check
        run: |
          if compgen -G "*.sln" > /dev/null; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run dotnet format
        id: formatter
        if: steps.sln_check.outputs.found == 'true'
        continue-on-error: true
        run: dotnet format --verify-no-changes --verbosity minimal

      - name: Comment on PR if formatting failed
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const { owner, repo, number } = context.issue;
            const message = `❌ **dotnet format** failed — please run \`dotnet format\` locally and commit the changes.`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: message
            });

      - name: Skip dotnet format (no .sln found)
        if: steps.sln_check.outputs.found == 'false'
        run: echo "ℹ️ No .sln found — skipping static analysis"
