name: 📣 Step 5 - Notify

on:
  workflow_call:
    inputs:
      title:
        description: "Notification title (e.g., Build Succeeded)"
        required: true
        type: string
      message:
        description: "Main content of the notification"
        required: true
        type: string
      status:
        description: "success | failure | neutral"
        required: false
        default: "neutral"
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📢 Send Slack Notification (if configured)
        if: ${{ env.SLACK_WEBHOOK != '' }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*${{ inputs.title }}* - `${{ github.repository }}`",
              "attachments": [
                {
                  "text": "${{ inputs.message }}",
                  "color": "${{ inputs.status == 'success' && 'good' || inputs.status == 'failure' && 'danger' || '#cccccc' }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: 📢 Send Discord Notification (if configured)
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"GitHub CI\",\"embeds\":[{\"title\":\"${{ inputs.title }}\",\"description\":\"${{ inputs.message }}\",\"color\":${{ inputs.status == 'success' && 3066993 || inputs.status == 'failure' && 15158332 || 9807270 }} }]}" \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}