name: 📋 Step 1 - Test

on:
  workflow_call:
    inputs:
      unityVersion:
        description: "Unity version to use"
        required: false
        default: 'auto'
        type: string
      useGitLfs:
        description: "Whether to use Git LFS (true/false)"
        required: false
        default: 'true'
        type: string
      editModePath:
        description: "Path to the EditMode tests folder"
        required: false
        default: 'Assets/Tests/Editor'
        type: string
      playModePath:
        description: "Path to the PlayMode tests folder"
        required: false
        default: 'Assets/Tests/PlayMode'
        type: string
      timeoutMinutes:
        description: "Timeout for each test job in minutes"
        type: number
        required: false
        default: 15
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true

jobs:
  detect-tests:
    name: 🔍 Detect Tests
    uses: ./.github/workflows/unity-tests-detection.yml
    with:
      editModePath: ${{ inputs.editModePath }}
      playModePath: ${{ inputs.playModePath }}

  run-editmode:
    name: 🥪 EditMode Tests
    needs: [detect-tests]
    if: needs.detect-tests.outputs.has_editmode == 'true'
    uses: ./.github/workflows/unity-tests-runner.yml
    with:
      testMode: EditMode
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
      timeoutMinutes: ${{ inputs.timeoutMinutes }}
    secrets: inherit

  run-playmode:
    name: 🎮 PlayMode Tests
    needs: [detect-tests]
    if: needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-tests-runner.yml
    with:
      testMode: PlayMode
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
      timeoutMinutes: ${{ inputs.timeoutMinutes }}
    secrets: inherit

  summarize-tests:
    name: 📄 Summarize Test Results
    if: always()
    runs-on: ubuntu-latest
    needs: [run-editmode, run-playmode]
    steps:
      - name: Write Summary
        run: |
          echo "### 📋 Unity Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test Mode   | Result     | Duration | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------------|------------|----------|--------|" >> $GITHUB_STEP_SUMMARY

          summarize() {
            local MODE=$1
            local ICON=$2
            local TOTAL=$3
            local PASSED=$4
            local RESULT=$5
            local DURATION=$6

            local DISPLAY_RESULT="${PASSED} / ${TOTAL}"
            local DISPLAY_DURATION="$DURATION"
            local STATUS="❌"
          
            if [[ "$RESULT" == "Skipped" || "$TOTAL" == "0" ]]; then
              DISPLAY_RESULT="-/-"
              DISPLAY_DURATION="N/A"
              STATUS="ℹ️"
            elif [[ "$RESULT" == "Passed" ]]; then
              STATUS="✔️"
            fi
          
            echo "| ${ICON} ${MODE} | ${DISPLAY_RESULT} | ${DISPLAY_DURATION} | ${STATUS} |" >> $GITHUB_STEP_SUMMARY
          }

          summarize "EditMode" "🥪" \
            "${{ needs.run-editmode.outputs.total }}" \
            "${{ needs.run-editmode.outputs.passed }}" \
            "${{ needs.run-editmode.outputs.result }}" \
            "${{ needs.run-editmode.outputs.duration }}"

          summarize "PlayMode" "🎮" \
            "${{ needs.run-playmode.outputs.total }}" \
            "${{ needs.run-playmode.outputs.passed }}" \
            "${{ needs.run-playmode.outputs.result }}" \
            "${{ needs.run-playmode.outputs.duration }}"

      - name: Download Test Result Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-results

      - name: Append Failed Test Details
        id: failed-check
        if: always()
        continue-on-error: true
        run: |
          set +e  # Don't exit script on errors
          HAS_FAILS=0
          FAIL_BLOCK=""

          for MODE in EditMode PlayMode; do
            XML=$(find downloaded-results -type f -path "*Unity-${MODE}-*" -name "*.xml" | head -n 1)

            if [[ -f "$XML" ]]; then
              FAILS=$(grep -oP 'test-case[^>]+result="Failed"' "$XML" | grep -oP 'fullname="\K[^"]+')
              if [[ -n "$FAILS" ]]; then
                HAS_FAILS=1
                FAIL_BLOCK+="### ❌ ${MODE} Failed Tests"$'\n'
                while read -r fail; do
                  FAIL_BLOCK+="- \`$fail\`"$'\n'
                done <<< "$FAILS"
                FAIL_BLOCK+=$'\n'
              fi
            fi
          done

          if [[ "$HAS_FAILS" == "1" ]]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "<details>" >> $GITHUB_STEP_SUMMARY
            echo "<summary>❌ Failed Tests (details)</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "$FAIL_BLOCK" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi

          echo "has_fails=$HAS_FAILS" >> $GITHUB_OUTPUT

      - name: Fail pipeline if tests failed
        if: steps.failed-check.outputs.has_fails == '1'
        run: |
          echo "❌ Unity tests failed."
          exit 1
