name: 🧪 Test Reusable Unity Test Runner

on:
  workflow_dispatch:

jobs:
  activate-unity:
    name: 🔐 Activate Unity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload Unity License File
        run: |
          echo "🔍 Searching for license file..."
          FOUND=$(find $HOME -type f -name 'Unity_lic.ulf' | head -n 1)
          if [ -z "$FOUND" ]; then
            echo "❌ License file not found"
            exit 1
          else
            echo "✅ Found at $FOUND"
            mkdir -p license
            cp "$FOUND" license/
          fi

      - name: Upload License Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-license
          path: license/Unity_lic.ulf

  run-editmode:
    name: Run EditMode Tests
    needs: activate-unity
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode
    secrets: inherit

  run-playmode:
    name: Run PlayMode Tests
    needs: activate-unity
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
    secrets: inherit