name: 🧠 Step 0 - Roslyn Lint (CSharpier)

on:
  workflow_call:
    inputs:
      allowAutofix:
        description: "Whether to allow auto-formatting and commit"
        required: false
        default: false
        type: boolean

jobs:
  roslyn-lint:
    name: 🧠 C# Code Lint (No MSBuild)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install CSharpier
        run: |
          dotnet tool install -g csharpier
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Check C# formatting (CSharpier)
        run: |
          echo "📂 Checking formatting in Assets/..."
          dotnet csharpier --check Assets

      - name: Auto-format C# files with CSharpier
        if: ${{ inputs.allowAutofix == true }}
        run: |
          echo "🛠️ Auto-formatting allowed. Applying changes..."
          dotnet csharpier Assets

      - name: Commit formatting fixes
        if: ${{ inputs.allowAutofix == true }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Assets
          git diff --cached --quiet || git commit -m "ROSLYN-AUTOFIX: auto-format C# files with CSharpier"
          git push || echo "⚠️ Could not push changes (probably a PR or no permission)"

      - name: Add Summary
        if: failure()
        run: |
          echo "❌ **CSharpier formatting issues detected**" >> $GITHUB_STEP_SUMMARY
          echo "Run \`dotnet csharpier .\` locally or re-run with \`allowAutofix: true\`." >> $GITHUB_STEP_SUMMARY
