name: 📋 Step 1 - Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  detect-tests:
    name: 🔍 Detect Tests
    uses: ./.github/workflows/detect-unity-tests.yml
    with:
      editModePath: Assets/Tests/Editor
      playModePath: Assets/Tests/PlayMode

  upload-license:
    name: ♻️ Upload Unity License
    needs: detect-tests
    if: needs.detect-tests.outputs.has_editmode == 'true' || needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/upload-unity-license.yml  
    with:
      artifactName: unity-license
    secrets: inherit

  run-editmode:
    name: 🥪 EditMode Tests
    continue-on-error: false
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_editmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode
    secrets: inherit

  run-playmode:
    name: 🎮 PlayMode Tests
    continue-on-error: false
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
    secrets: inherit