name: 📋 Step 1 - Tests

on:
  workflow_call:
    inputs:
      unityVersion:
        description: "Unity version to use"
        required: true
        default: 'auto'
        type: string
      licenseArtifactName:
        description: "Name of the uploaded license artifact"
        required: false
        default: 'unity-license'
        type: string
      useGitLfs:
        description: "Whether to use Git LFS (true/false)"
        required: false
        default: 'true'
        type: string
      editModePath:
        description: "Path to the EditMode tests folder"
        required: false
        default: 'Assets/Tests/Editor'
        type: string
      playModePath:
        description: "Path to the PlayMode tests folder"
        required: false
        default: 'Assets/Tests/PlayMode'
        type: string

jobs:
  detect-tests:
    name: 🔍 Detect Tests
    uses: ./.github/workflows/detect-unity-tests.yml
    with:
      editModePath: ${{ inputs.editModePath }}
      playModePath: ${{ inputs.playModePath }}

  upload-license:
    name: 📥️ Upload Unity License
    needs: detect-tests
    if: needs.detect-tests.outputs.has_editmode == 'true' || needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/upload-unity-license.yml
    with:
      artifactName: ${{ inputs.licenseArtifactName }}
    secrets: inherit

  run-editmode:
    name: 🥪 EditMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_editmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode
      licenseArtifactName: ${{ inputs.licenseArtifactName }}
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
    secrets: inherit

  run-playmode:
    name: 🎮 PlayMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
      licenseArtifactName: ${{ inputs.licenseArtifactName }}
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
    secrets: inherit