# .github/workflows/step-0-roslyn-analyze.yml
name: 🧠 Step 0 - Roslyn Lint (CSharpier)

on:
  workflow_call:

jobs:
  roslyn-lint:
    name: 🧠 C# Code Lint (No MSBuild)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install CSharpier
        run: dotnet tool install -g csharpier

      - name: Run CSharpier on Unity scripts
        run: |
          echo "📂 Scanning Assets..."
          csharpier --check Assets