name: ✨ Step 2 - Build

on:
  workflow_call:
    inputs:
      projectName:
        description: "The name of the built project i.e. 'My_Project' (avoid spaces)"
        default: "My_Project"
        type: string
        required: false
      buildType:
        description: "Build type, e.g. 'preview' or 'release'"
        type: string
        required: true
      targetPlatforms:
        description: "JSON array of platforms to build"
        type: string
        default: '["Android","WebGL","StandaloneLinux64","StandaloneWindows","StandaloneWindows64","StandaloneOSX","iOS"]'
        required: false
      timeoutMinutes:
        description: "Timeout for each build job in minutes"
        type: number
        default: 30
        required: false
      retentionDays:
          description: "How many days to keep the uploaded build artifacts (e.g. 7 for preview, 30 for release)"
          type: number
          default: 7
          required: false
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter_platforms:
    uses: ./.github/workflows/target-platforms-filter.yml
    with:
      targetPlatforms: ${{ inputs.targetPlatforms }}

  determine_version:
    uses: ./.github/workflows/build-version-generator.yml
    with:
      buildType: ${{ inputs.buildType }}

  build_on_macos:
    name: Build for ${{ matrix.targetPlatform }}
    if: needs.filter_platforms.outputs.macPlatforms != '[]'
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ inputs.timeoutMinutes }}
    needs: [filter_platforms, determine_version]
    strategy:
      fail-fast: false
      matrix:
        os: 
          - macOS-latest
        targetPlatform: ${{ fromJson(needs.filter_platforms.outputs.macPlatforms) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Unity Library Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.projectName }}_${{ matrix.targetPlatform }}-${{ needs.determine_version.outputs.version }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: ${{ inputs.retentionDays }}

  build_on_ubuntu:
    name: Build for ${{ matrix.targetPlatform }}
    if: needs.filter_platforms.outputs.ubuntuPlatforms != '[]'
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ inputs.timeoutMinutes }}
    needs: [filter_platforms, determine_version]
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        targetPlatform: ${{ fromJson(needs.filter_platforms.outputs.ubuntuPlatforms) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Unity Library Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - name: Check Free Disk Space (Android only)
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.projectName }}_${{ matrix.targetPlatform }}-${{ needs.determine_version.outputs.version }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: ${{ inputs.retentionDays }}

  confirm_builds:
    name: 📄 Summarize Build Results
    if: always()
    runs-on: ubuntu-latest
    needs: [build_on_ubuntu, build_on_macos, filter_platforms]
    steps:
      - name: Write Build Summary
        run: |
          echo "### ✅ Unity Build Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          HAS_UBUNTU=${{ needs.build_on_ubuntu.result != 'skipped' }}
          HAS_MACOS=${{ needs.build_on_macos.result != 'skipped' }}

          if [[ "$HAS_UBUNTU" == "false" && "$HAS_MACOS" == "false" ]]; then
            echo "- ℹ️ No builds detected for Ubuntu or macOS." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          if [[ "$HAS_UBUNTU" == "true" ]]; then
            echo "- 🐧 Ubuntu Builds: ${{ needs.build_on_ubuntu.result == 'success' && '✅ Success' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "$HAS_MACOS" == "true" ]]; then
            echo "- 🍏 macOS Builds: ${{ needs.build_on_macos.result == 'success' && '✅ Success' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          fi