name: 📋 Step 1 - Test

on:
  workflow_call:
    inputs:
      unityVersion:
        description: "Unity version to use"
        required: false
        default: 'auto'
        type: string
      licenseArtifactName:
        description: "Name of the uploaded license artifact"
        required: false
        default: 'unity-license'
        type: string
      useGitLfs:
        description: "Whether to use Git LFS (true/false)"
        required: false
        default: 'true'
        type: string
      editModePath:
        description: "Path to the EditMode tests folder"
        required: false
        default: 'Assets/Tests/Editor'
        type: string
      playModePath:
        description: "Path to the PlayMode tests folder"
        required: false
        default: 'Assets/Tests/PlayMode'
        type: string
      timeoutMinutes:
        description: "Timeout for each test job in minutes"
        type: number
        required: false
        default: 15
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true

# ─────────────────────────────────────────────────────────────────────────────
# Environment variables
# ─────────────────────────────────────────────────────────────────────────────
env:
  UNITY_VERSION: ${{ inputs.unityVersion }}
  LICENSE_ARTIFACT_NAME: ${{ inputs.licenseArtifactName }}
  USE_GIT_LFS: ${{ inputs.useGitLfs }}
  EDIT_MODE_TEST_PATH: ${{ inputs.editModePath }}
  PLAY_MODE_TEST_PATH: ${{ inputs.playModePath }}
  TIMEOUT_MINUTES: ${{ inputs.timeoutMinutes }}

jobs:
  detect-tests:
    name: 🔍 Detect Tests
    uses: ./.github/workflows/unity-tests-detection.yml
    with:
      editModePath: ${{ env.EDIT_MODE_TEST_PATH }}
      playModePath: ${{ env.PLAY_MODE_TEST_PATH }}

  upload-license:
    name: 📥️ Upload Unity License
    needs: detect-tests
    if: needs.detect-tests.outputs.has_editmode == 'true' || needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-license-uploader.yml
    with:
      artifactName: ${{ env.LICENSE_ARTIFACT_NAME }}
    secrets: inherit

  run-editmode:
    name: 🥪 EditMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_editmode == 'true'
    uses: ./.github/workflows/unity-tests-runner.yml
    with:
      testMode: EditMode
      licenseArtifactName: ${{ env.LICENSE_ARTIFACT_NAME }}
      unityVersion: ${{ env.UNITY_VERSION }}
      useGitLfs: ${{ env.USE_GIT_LFS }}
      timeoutMinutes: ${{ env.TIMEOUT_MINUTES }}
    secrets: inherit

  run-playmode:
    name: 🎮 PlayMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-tests-runner.yml
    with:
      testMode: PlayMode
      licenseArtifactName: ${{ env.LICENSE_ARTIFACT_NAME }}
      unityVersion: ${{ env.UNITY_VERSION }}
      useGitLfs: ${{ env.USE_GIT_LFS }}
      timeoutMinutes: ${{ env.TIMEOUT_MINUTES }}
    secrets: inherit
