name: 📋 Step 1 - Test

on:
  workflow_call:
    inputs:
      unityVersion:
        description: "Unity version to use"
        required: false
        default: 'auto'
        type: string
      useGitLfs:
        description: "Whether to use Git LFS (true/false)"
        required: false
        default: 'true'
        type: string
      editModePath:
        description: "Path to the EditMode tests folder"
        required: false
        default: 'Assets/Tests/Editor'
        type: string
      playModePath:
        description: "Path to the PlayMode tests folder"
        required: false
        default: 'Assets/Tests/PlayMode'
        type: string
      timeoutMinutes:
        description: "Timeout for each test job in minutes"
        required: false
        default: 15
        type: number
      quietMode:
        description: "Enable quiet mode to suppress uploads/logs unless tests fail"
        required: false
        default: 'false'
        type: string
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true

jobs:
  upload_unity_license:
    name: 📥️ Upload Unity License
    uses: ./.github/workflows/unity-license-uploader.yml
    secrets:
      inherit

  detect_tests:
    name: 🔍 Detect Tests
    uses: ./.github/workflows/unity-tests-detection.yml
    with:
      editModePath: ${{ inputs.editModePath }}
      playModePath: ${{ inputs.playModePath }}

  run-editmode:
    name: 🥪 EditMode Tests
    needs: 
      - detect_tests
      - upload_unity_license
    if: needs.detect_tests.outputs.has_editmode == 'true'
    uses: ./.github/workflows/unity-tests-runner.yml
    with:
      testMode: EditMode
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
      timeoutMinutes: ${{ inputs.timeoutMinutes }}
      quietMode: ${{ inputs.quietMode }}
    secrets: inherit

  run-playmode:
    name: 🎮 PlayMode Tests
    needs: 
      - detect_tests
      - upload_unity_license
    if: needs.detect_tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-tests-runner.yml
    with:
      testMode: PlayMode
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
      timeoutMinutes: ${{ inputs.timeoutMinutes }}
      quietMode: ${{ inputs.quietMode }}
    secrets: inherit

  summarize-tests:
    name: 📄 Summarize Test Results
    needs: [run-editmode, run-playmode]
    if: |
      always() &&
      (
        inputs.quietMode == 'false' ||
        (needs.run-editmode.result == 'success' && needs.run-editmode.outputs.failed == 'true') ||
        (needs.run-playmode.result == 'success' && needs.run-playmode.outputs.failed == 'true')
      )
    uses: ./.github/workflows/summarize-tests.yml
    with:
      quietMode: ${{ inputs.quietMode }}
      editmodeFailed: ${{ needs.run-editmode.outputs.failed }}
      playmodeFailed: ${{ needs.run-playmode.outputs.failed }}
      editmodeTotal: ${{ needs.run-editmode.outputs.total }}
      editmodePassed: ${{ needs.run-editmode.outputs.passed }}
      editmodeResult: ${{ needs.run-editmode.outputs.result }}
      editmodeDuration: ${{ needs.run-editmode.outputs.duration }}
      playmodeTotal: ${{ needs.run-playmode.outputs.total }}
      playmodePassed: ${{ needs.run-playmode.outputs.passed }}
      playmodeResult: ${{ needs.run-playmode.outputs.result }}
      playmodeDuration: ${{ needs.run-playmode.outputs.duration }}