# .github/workflows/test-unity-tests.yml
name: 🧪 Test Reusable Unity Test Runner

on:
  workflow_dispatch:

jobs:
  activate-unity:
    name: 🔐 Activate Unity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  run-editmode:
    needs: activate-unity
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode

  run-playmode:
    needs: activate-unity
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
