name: ✨ Step 1 - Tests

on:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: |
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id || true

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: git lfs pull

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run Tests
        id: run-tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}          
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: failure() && steps.run-tests.outputs.artifactsPath != ''
        with:
          name: Test Results
          path: ${{ steps.run-tests.outputs.artifactsPath }}
          retention-days: 3

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        if: success() && steps.run-tests.outputs.artifactsPath != ''
        with:
          name: Code Coverage
          path: ${{ steps.run-tests.outputs.artifactsPath }}/**/CoverageResults
          retention-days: 3

      - name: Check for Test Results
        if: failure()
        run: |
          if [ -z "${{ steps.run-tests.outputs.artifactsPath }}" ]; then
            echo "⚠️ No test results found. Maybe test step was skipped or failed early."
          else
            echo "✅ Test results located at: ${{ steps.run-tests.outputs.artifactsPath }}"
          fi