name: 📋 Step 1: Tests

on:
  workflow_dispatch:
    inputs:
      unityVersion:
        description: "Unity version to use"
        required: true
        default: 'auto'
      licenseArtifactName:
        description: "Name of the uploaded license artifact"
        required: false
        default: 'unity-license'
      useGitLfs:
        description: "Whether to use Git LFS (true/false)"
        required: false
        default: 'true'
      editModePath:
        description: "Path to the EditMode tests folder"
        required: false
        default: 'Assets/Tests/Editor'
      playModePath:
        description: "Path to the PlayMode tests folder"
        required: false
        default: 'Assets/Tests/PlayMode'     

  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  detect-tests:
    name: 🔍 Detect Tests
    uses: avalin/unity-ci-templates/.github/workflows/detect-unity-tests.yml@main
    with:
      editModePath: ${{ inputs.editModePath }}
      playModePath: ${{ inputs.playModePath }}

  upload-license:
    name: 📥️ Upload Unity License
    needs: detect-tests
    if: needs.detect-tests.outputs.has_editmode == 'true' || needs.detect-tests.outputs.has_playmode == 'true'
    uses: avalin/unity-ci-templates/.github/workflows/upload-unity-license.yml@main
    with:
      artifactName: ${{ inputs.licenseArtifactName }}
    secrets: inherit

  run-editmode:
    name: 🥪 EditMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_editmode == 'true'
    uses: avalin/unity-ci-templates/.github/workflows/unity-test-runner.yml@main
    with:
      testMode: EditMode
      licenseArtifactName: ${{ inputs.licenseArtifactName }}
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
    secrets: inherit

  run-playmode:
    name: 🎮 PlayMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_playmode == 'true'
    uses: avalin/unity-ci-templates/.github/workflows/unity-test-runner.yml@main
    with:
      testMode: PlayMode
      licenseArtifactName: ${{ inputs.licenseArtifactName }}
      unityVersion: ${{ inputs.unityVersion }}
      useGitLfs: ${{ inputs.useGitLfs }}
    secrets: inherit