name: 🚀 Stripped CI/CD Pipeline (No Tests)

on:
  # Allow manual dispatch with a buildType input
  workflow_dispatch:
    inputs:
      buildType:
        description: "Choose build type"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release
      targetPlatforms:
        description: "JSON array of platforms to build"
        type: string
        default: '["Android","iOS"]'
        required: false

  # Automatically run tests & builds on certain branches or PR changes
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  # Step 2: Build (Tests Skipped)
  build:
    name: Build
    # Only build if:
    # - We have a pull request
    # - We have manual dispatch (either preview or release)
    # - We are pushing to "main"
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch') ||
      github.ref == 'refs/heads/main'
    uses: ./.github/workflows/step-2-build.yml
    with:
      buildType: ${{ github.event.inputs.buildType }}
      targetPlatforms: ${{ github.event.inputs.targetPlatforms }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}