name: 🧪 Test Build & Release Workflow

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: 'preview' | 'release_candidate' | 'release'"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release_candidate
          - release
      version:
        description: "Optional version string (e.g. v1.2.3 or v1.2.3-rc.1). Leave blank to auto-generate (e.g. PR-0001, manual-main)"
        required: false
        default: ""
        type: string
      projectName:
        description: "Project name for artifacts"
        required: true
        default: "Unity_CI_Templates"
      targetPlatforms:
        description: "JSON array of platforms to build"
        required: true
        default: '["WebGL", "StandaloneWindows64"]'
      deployTargets:
        description: "JSON array of deploy targets (e.g. ['itch.io','s3'])"
        required: false
        default: '[]'

permissions:
  contents: write

jobs:
  setup-prerequisites:
    name: ⏳ Setup Prerequisites
    uses: avalin/unity-ci-templates/.github/workflows/ci-cd-prerequisites.yml@main
    with:
      excludesUnityTests: "true"
      deployTargets: ${{ inputs.deployTargets }}
    secrets: inherit

  build:
    name: 🧩 Trigger Unity Build (Step 2)
    needs: setup-prerequisites
    uses: ./.github/workflows/step-2-build.yml
    with:
      buildType: ${{ inputs.buildType }}
      version: ${{ inputs.version }}
      projectName: ${{ inputs.projectName }}
      targetPlatforms: ${{ inputs.targetPlatforms }}
      combineArtifacts: ${{ needs.setup-prerequisites.outputs.requiresCombinedArtifact }}
    secrets: inherit

  release:
    name: 📦 Trigger GitHub Release (Step 3)
    needs: [ setup-prerequisites, build ]
    if: ${{ inputs.buildType == 'release' || inputs.buildType == 'release_candidate' }}
    uses: ./.github/workflows/step-3-release.yml
    with:
      buildType: ${{ inputs.buildType }}
      version: ${{ needs.build.outputs.version }}
      projectName: ${{ inputs.projectName }}
      targetPlatforms: ${{ inputs.targetPlatforms }}
      combineArtifacts: ${{ needs.setup-prerequisites.outputs.requiresCombinedArtifact }}
      skipPerPlatformArtifacts: ${{ needs.setup-prerequisites.outputs.skipPerPlatformArtifacts }}  
    secrets: inherit
