name: 🧪 Test Tests Workflow

on:
  workflow_dispatch:
    inputs:
      timeoutMinutes:
        description: "Minutes until tests fail on timeout"
        required: false
        default: "15"
        type: string
      quietMode:
        description: "Enable quiet mode to suppress uploads/logs unless tests fail"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare_metadata:
    name: ⏳ Prepare Metadata
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      skipTests: false
      testsOnly: true
      deployTargets: '[]'
      buildType: 'preview'
      version: 'v0.0.0'

  test-run-tests:
    name: Test Run Tests
    needs: prepare_metadata
    uses: avalin/unity-ci-templates/.github/workflows/step-1-test.yml@main
    with:
      unityVersion: ${{ needs.prepare_metadata.outputs.unityVersion }}
      useGitLfs: ${{ needs.prepare_metadata.outputs.useGitLfs }}
      editModePath: ${{ needs.prepare_metadata.outputs.editModePath }}
      playModePath: ${{ needs.prepare_metadata.outputs.playModePath }}
      timeoutMinutes: ${{ fromJson(inputs.timeoutMinutes) }}
      quietMode: ${{ inputs.quietMode }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
