name: 🧪 Test Tests Workflow

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test-run-tests:
    name: Test Run Tests
    uses: avalin/unity-ci-templates/.github/workflows/step-1-test.yml@main
    with:
      unityVersion: ${{ vars.UNITY_VERSION }}
      licenseArtifactName: ${{ vars.LICENSE_ARTIFACT_NAME }}
      useGitLfs: ${{ vars.USE_GIT_LFS }}
      editModePath: ${{ vars.UNITY_TESTS_EDITMODE_PATH }}
      playModePath: ${{ vars.UNITY_TESTS_PLAYMODE_PATH }}
      timeoutMinutes: ${{ fromJson(vars.TIMEOUT_TESTS_IN_MINUTES) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
