name: 🧪 Test Tests Workflow

on:
  workflow_dispatch:
    inputs:
      quietMode:
        description: "Enable quiet mode to suppress uploads/logs unless tests fail"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare_metadata:
    name: ⏳ Prepare Metadata
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      skipTests: false
      testsOnly: true
      deployTargets: '[]'
      buildType: 'preview'
      version: 'v0.0.0'

  test-run-tests:
    name: Test Run Tests
    needs: [ prepare_metadata ]
    uses: avalin/unity-ci-templates/.github/workflows/step-1-test.yml@main
    with:
      unityVersion: ${{ vars.UNITY_VERSION || 'auto' }}
      useGitLfs: ${{ vars.USE_GIT_LFS || 'false' }}
      editModePath: ${{ vars.UNITY_TESTS_EDITMODE_PATH || 'Assets/Tests/Editor' }}
      playModePath: ${{ vars.UNITY_TESTS_PLAYMODE_PATH || 'Assets/Tests/PlayMode' }}
      timeoutMinutes: ${{ fromJson(vars.TIMEOUT_TESTS_IN_MINUTES || '15') }}
      quietMode: ${{ inputs.quietMode }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
