name: 🧪 Test - Prepare Metadata Workflow

on:
  workflow_dispatch:
    inputs:
      unityVersion:
        description: "Specific unity version to test on"
        required: false
        default: "auto"
        type: string      
      buildVersion:
        description: "Optional base version (e.g., v1.2.3) for release candidate"
        required: false
      buildType:
        description: "Build type"
        required: false
        type: choice
        options:
          - preview
          - release_candidate
          - release
        default: preview
      skipTests:
        description: "Whether tests should be skipped"
        required: true
        default: "false"
        type: choice
        options:
          - 'true'
          - 'false'
      deployTargets:
        description: "JSON array of deploy targets (e.g. [\"itch.io\",\"s3\"])"
        required: true
        default: '["steam", "gh-pages"]'
      quietMode:
        description: "Enable quiet mode to suppress uploads/logs unless tests fail"
        required: true
        default: "default"
        type: choice
        options:
          - "default"
          - "true"
          - "false"

permissions:
  contents: read
  pull-requests: write

jobs:
  prepare-metadata:
    name: ⏳ Prepare Metadata
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      unityVersion: ${{ inputs.unityVersion }}
      projectName: ${{ vars.PROJECT_NAME }}
      skipTests: ${{ inputs.skipTests }}
      deployTargets: ${{ inputs.deployTargets }}
      buildType: ${{ inputs.buildType }}
      buildVersion: ${{ inputs.buildVersion }}
      quietMode: ${{ inputs.quietMode }}