name: 🧪 Test Tests Workflow

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  add-prerequisites:
    name: Add Prerequisites
    uses: avalin/unity-ci-templates/.github/workflows/ci-cd-prerequisites.yml@main
    with:
      excludesUnityTests: "false"
    secrets: inherit

  test-run-tests:
    name: Test Run Tests
    needs: [ add-prerequisites ]
    uses: avalin/unity-ci-templates/.github/workflows/step-1-test.yml@main
    with:
      unityVersion: ${{ vars.UNITY_VERSION || 'auto' }}
      useGitLfs: ${{ vars.USE_GIT_LFS || 'false' }}
      editModePath: ${{ vars.UNITY_TESTS_EDITMODE_PATH || 'Assets/Tests/Editor' }}
      playModePath: ${{ vars.UNITY_TESTS_PLAYMODE_PATH || 'Assets/Tests/PlayMode' }}
      timeoutMinutes: ${{ fromJson(vars.TIMEOUT_TESTS_IN_MINUTES || '15') }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
