name: 🧪 Test Build & Release Workflow

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: 'preview' for manual/dev builds, 'release_candidate' for staging (e.g., v1.2.3-rc.1), 'release' for production (e.g., v1.2.3)"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release_candidate
          - release
      version:
        description: "Optional version string (e.g. v1.2.3 or v1.2.3-rc.1). Leave blank to auto-generate (e.g. PR-0001, manual-main)"
        required: false
        default: ""
      projectName:
        description: "Project name for artifacts"
        required: true
        default: "Unity_CI_Templates"
      targetPlatforms:
        description: "JSON array of platforms to build"
        required: true
        default: '["WebGL", "StandaloneWindows64"]'
      deployTargets:
        description: "JSON array of deploy targets (e.g. ['itch.io','s3'])"
        required: false
        default: '[]'

permissions:
  contents: write

jobs:
  setup-prerequisites:
    name: ⏳ Setup Prerequisites
    uses: avalin/unity-ci-templates/.github/workflows/ci-cd-prerequisites.yml@main
    with:
      excludesUnityTests: "true"
      deployTargets: ${{ inputs.deployTargets }}
    secrets: inherit

  build:
    name: 🧩 Trigger Unity Build (Step 2)
    needs: setup-prerequisites
    uses: ./.github/workflows/step-2-build.yml
    with:
      buildType: ${{ inputs.buildType }}
      projectName: ${{ inputs.projectName }}
      targetPlatforms: ${{ inputs.targetPlatforms }}
      combineArtifacts: ${{ fromJSON(needs.setup-prerequisites.outputs.requiresCombinedArtifact) }}
    secrets: inherit

  release:
    name: 📦 Trigger GitHub Release (Step 3)
    if: ${{ inputs.buildType == 'release' || inputs.buildType == 'release_candidate' }}
    needs: [ setup-prerequisites, build ]
    uses: ./.github/workflows/step-3-release.yml
    with:
      buildType: ${{ inputs.buildType }}
      version: ${{ needs.build.outputs.version }}
      projectName: ${{ inputs.projectName }}
      targetPlatforms: ${{ inputs.targetPlatforms }}
      combineArtifacts: ${{ fromJSON(needs.setup-prerequisites.outputs.requiresCombinedArtifact) }}
      skipPerPlatformArtifacts: ${{ fromJSON(needs.setup-prerequisites.outputs.skipPerPlatformArtifacts) }}
    secrets: inherit
