name: 🧪 Test Prepare Metadata

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Optional base version (e.g., v1.2.3) for release candidate"
        required: false
      buildType:
        description: "Build type"
        required: false
        type: choice
        options:
          - preview
          - release_candidate
          - release
        default: preview
      skipTests:
        description: "Whether tests should be skipped"
        required: true
        default: "false"
        type: choice
        options:
          - 'true'
          - 'false'
      deployTargets:
        description: "JSON array of deploy targets (e.g. [\"itch.io\",\"s3\"])"
        required: true
        default: '["steam", "gh-pages"]'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Validate required secrets
        run: |
          REQUIRED_SECRETS=$(echo '${{ inputs.requiredSecrets }}' | jq -r '.[]')
          MISSING=0

          for SECRET_NAME in $REQUIRED_SECRETS; do
            VALUE="${{ secrets[SECRET_NAME] }}"
            if [[ -z "$VALUE" || "$VALUE" == "" ]]; then
              echo "❌ Required secret '$SECRET_NAME' is not set!"
              MISSING=1
            else
              echo "✅ Secret '$SECRET_NAME' is present."
            fi
          done

          if [[ "$MISSING" -eq 1 ]]; then
            echo "❌ One or more required secrets are missing. Failing..."
            exit 1
          fi

  prepare-metadata:
    name: ⏳ Prepare Metadata
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      skipTests: ${{ inputs.skipTests }}
      deployTargets: ${{ inputs.deployTargets }}
      buildType: ${{ inputs.buildType }}
      version: ${{ inputs.version }}