name: 🧪 Test - Step 5 Notify Workflow

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: 'preview' for manual/dev builds, 'release_candidate' for staging (e.g., v1.2.3-rc.1), 'release' for production (e.g., v1.2.3)"
        required: true
        default: "release_candidate"
        type: choice
        options:
          - preview
          - release_candidate
          - release
      artifactSource:
        description: "Whether deployment files comes from a fresh build or an existing release"
        required: true
        default: "build"
        type: choice
        options:
          - build
          - release
      version:
        description: "Optional version string (e.g. v1.2.3 or v1.2.3-rc.1). Leave blank to auto-generate (e.g. PR-0001, manual-main)"
        required: false
        default: "v0.0.0"
        type: string
      projectName:
        description: "Project name for artifacts"
        required: true
        default: "Unity_CI_Templates"
      targetPlatforms:
        description: "JSON array of platforms to build"
        required: true
        default: '["Android", "WebGL", "StandaloneLinux64", "StandaloneWindows", "StandaloneWindows64", "StandaloneOSX", "iOS"]'
      deployTargets:
        description: "JSON array of deploy targets (e.g. [\"itch.io\",\"s3\"])"
        required: true
        default: '["itch.io", "appcenter", "firebase", "s3", "gh-pages", "steam", "discord", "testflight", "custom-server"]'
        type: string
      editmodeFailedCount:
        description: "Number of simulated EditMode test failures"
        required: false
        default: '0'
        type: string
      editmodeTotalCount:
        description: "Simulated total EditMode tests"
        required: false
        default: '12'
        type: string
      playmodeFailedCount:
        description: "Number of simulated PlayMode test failures"
        required: false
        default: '0'
        type: string
      playmodeTotalCount:
        description: "Simulated total PlayMode tests"
        required: false
        default: '12'
        type: string

permissions:
  contents: write

jobs:
  prepare_metadata:
    name: ⏳ Prepare Metadata
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      skipTests: true
      testsOnly: false
      deployTargets: ${{ inputs.deployTargets }}
      buildType: ${{ inputs.buildType }}
      version: ${{ inputs.version }}

  dry_build:
    name: 🧩 Create Dry-Build
    needs: prepare_metadata
    if:  ${{ inputs.artifactSource == 'build' }}
    uses: ./.github/workflows/dry-build.yml
    with:
      version: ${{ needs.prepare_metadata.outputs.version }}
      projectName: ${{ inputs.projectName }}
      targetPlatforms: ${{ inputs.targetPlatforms }}
      combineArtifacts: ${{ needs.prepare_metadata.outputs.requiresCombined }}
    secrets: inherit