name: 🧪 Test Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The GitHub release tag (e.g. v0.1.2-ekans)"
        required: true
      projectName:
        description: "Project name used in the release file naming (e.g. Unity_CI_Templates)"
        default: "Unity_CI_Templates"
        required: true
      deployTargets:
        description: "JSON array of deploy targets"
        default: '["gh-pages"]'
        required: true
jobs:
  deploy:
    uses: ./.github/workflows/step-4-deploy.yml
    with:
      buildType: release
      version: ${{ inputs.version }}
      projectName: ${{ inputs.projectName }}
      deployTargets: ${{ inputs.deployTargets }}
      artifactSource: release
    secrets: inherit
