name: 🧪 Test Analyze Workflow

on:
  workflow_dispatch:
    inputs:
      allowAutofix:
        description: "Whether to allow autofixing lint issues on PR"
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      allowFailure:
        description: "Whether failed formatting should be allowed"
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  test-analyze:
    name: Analyze with Roslynator
    uses: avalin/unity-ci-templates/.github/workflows/step-0-roslyn-analyze.yml@main
    with:
      allowAutofix: ${{ inputs.allowAutofix == 'true' }}
      allowFailure: ${{ inputs.allowFailure == 'true' }}
