name: 🧪 Test Analyze & Tests Workflow

on:
  workflow_dispatch:
    inputs:
        allowAutofix:
            description: "Whether to allow autofixing lint issues on PR"
            required: false
            default: 'false'
            type: choice
            options:
              - 'true'
              - 'false'
        allowFail:
            description: "Whether lint errors should fail the pipeline"
            required: false
            default: 'true'
            type: choice
            options:
            - 'true'
            - 'false'

permissions:
  contents: write
  pull-requests: write

jobs:
  test-analyze:
    name: Test Static Analysis
    uses: avalin/unity-ci-templates/.github/workflows/step-0-analyze.yml@main
    with:
      allowAutofix: ${{ inputs.allowAutofix }}
      allowFail: ${{ inputs.allowFail }}

  test-run-tests:
    name: Test Run Tests
    needs: [ test-analyze ]
    uses: avalin/unity-ci-templates/.github/workflows/step-1-test.yml@main
    with:
      unityVersion: ${{ vars.UNITY_VERSION }}
      licenseArtifactName: ${{ vars.LICENSE_ARTIFACT_NAME }}
      useGitLfs: ${{ vars.USE_GIT_LFS }}
      editModePath: ${{ vars.UNITY_TESTS_EDITMODE_PATH }}
      playModePath: ${{ vars.UNITY_TESTS_PLAYMODE_PATH }}
      timeoutMinutes: ${{ fromJson(vars.TIMEOUT_TESTS_IN_MINUTES) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
