name: 📊 Unity Tests Runner

on:
  workflow_call:
    inputs:
      testMode:
        description: "Unity test mode to run (EditMode or PlayMode)"
        required: true
        type: string
      unityVersion:
        description: "Unity version to use"
        required: true
        type: string
      useGitLfs:
        description: "Whether to use Git LFS (true/false)"
        required: true
        type: string
      licenseArtifactName:
        description: "Name of uploaded license artifact"
        required: true
        type: string
      timeoutMinutes:
        description: "Timeout for each build job in minutes"
        type: number
        required: true
    outputs:
      artifactsPath:
        description: "Path to test artifacts"
        value: ${{ jobs.run-tests.outputs.artifactsPath }}
      resultSummary:
        description: "Summary of passed/total tests"
        value: ${{ jobs.run-tests.outputs.resultSummary }}
      durationMinutes:
        description: "Total test duration in minutes"
        value: ${{ jobs.run-tests.outputs.durationMinutes }}
jobs:
  run-tests:
    name: Run ${{ inputs.testMode }} Tests
    runs-on: ubuntu-latest
    outputs:
      artifactsPath: ${{ steps.run-tests.outputs.artifactsPath }}
      resultSummary: ${{ steps.extract-stats.outputs.resultSummary }}
      durationMinutes: ${{ steps.extract-stats.outputs.durationMinutes }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create LFS file list
        if: inputs.useGitLfs == 'true'
        run: |
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id || true

      - name: Restore LFS cache
        if: inputs.useGitLfs == 'true'
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        if: inputs.useGitLfs == 'true'
        run: git lfs pull

      - name: Download Unity License Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.licenseArtifactName }}
          path: ~/.local/share/unity3d/Unity

      - name: Cache Unity Packages
        uses: actions/cache@v4
        with:
          path: Packages
          key: Packages-${{ inputs.testMode }}-${{ hashFiles('Packages/**', 'Packages/manifest.json') }}
          restore-keys: |
            Packages-${{ inputs.testMode }}-

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ inputs.testMode }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ inputs.testMode }}-

      - name: Print Unity Version & Selected Test Mode
        shell: bash
        run: |
          echo "🛠 Using Unity version: ${{ inputs.unityVersion }}"
          echo "🧪 Running tests: ${{ inputs.testMode }}"

      - name: Run ${{ inputs.testMode }} Tests
        id: run-tests
        timeout-minutes: ${{ inputs.timeoutMinutes }}
        continue-on-error: false
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          testMode: ${{ inputs.testMode }}

      - name: Extract Test Stats & Duration
        if: always()
        id: extract-stats
        run: |
          FILE=$(find . -type f -name "TestResults.xml" | head -n 1)

          if [ -f "$FILE" ]; then
            TOTAL=$(xmllint --xpath "string(count(//test-case))" "$FILE")
            PASSED=$(xmllint --xpath "string(count(//test-case[@result='Passed']))" "$FILE")
            DURATION=$(xmllint --xpath "string(sum(//test-case/@duration))" "$FILE")
            DURATION_MIN=$(awk "BEGIN {printf \"%.2f\", $DURATION}")

            echo "resultSummary=$PASSED / $TOTAL" >> $GITHUB_OUTPUT
            echo "durationMinutes=$DURATION_MIN" >> $GITHUB_OUTPUT
          else
            echo "resultSummary=Unavailable" >> $GITHUB_OUTPUT
            echo "durationMinutes=Unavailable" >> $GITHUB_OUTPUT
          fi

      - name: Upload ${{ inputs.testMode }} Test Results (if tests failed)
        if: failure() && steps.run-tests.outputs.artifactsPath != ''
        uses: actions/upload-artifact@v4
        with:
          name: Unity-${{ inputs.testMode }}-${{ github.sha }}
          path: ${{ steps.run-tests.outputs.artifactsPath }}
          retention-days: 7

      - name: Log Result Path (if tests failed)
        if: failure()
        run: |
          if [ -z "${{ steps.run-tests.outputs.artifactsPath }}" ]; then
            echo "⚠️ No test results found. Maybe test step was skipped or failed early."
          else
            echo "✅ Test results located at: ${{ steps.run-tests.outputs.artifactsPath }}"
          fi