name: 📊 Unity Tests Runner

on:
  workflow_call:
    inputs:
      testMode:
        description: "Unity test mode to run (EditMode or PlayMode)"
        required: true
        type: string
      unityVersion:
        description: "Unity version to use"
        required: true
        type: string
      useGitLfs:
        description: "Whether to use Git LFS (true/false)"
        required: true
        type: string
      timeoutMinutes:
        description: "Timeout for each build job in minutes"
        type: number
        required: true
    outputs:
      total:
        description: "Total number of tests"
        value: ${{ jobs.run-tests.outputs.total }}
      passed:
        description: "Number of passed tests"
        value: ${{ jobs.run-tests.outputs.passed }}
      result:
        description: "Overall result (Passed, Failed, etc.)"
        value: ${{ jobs.run-tests.outputs.result }}
      durationSeconds:
        description: "Test duration in seconds"
        value: ${{ jobs.run-tests.outputs.durationSeconds }}
jobs:
  run-tests:
    name: Run ${{ inputs.testMode }} Tests
    runs-on: ubuntu-latest
    outputs:
      total: ${{ steps.summary.outputs.total }}
      passed: ${{ steps.summary.outputs.passed }}
      result: ${{ steps.summary.outputs.result }}
      durationSeconds: ${{ steps.summary.outputs.durationSeconds }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create LFS file list
        if: inputs.useGitLfs == 'true'
        run: |
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id || true

      - name: Restore LFS cache
        if: inputs.useGitLfs == 'true'
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        if: inputs.useGitLfs == 'true'
        run: git lfs pull

      - name: Download Unity License Artifact
        uses: actions/download-artifact@v4
        with:
          name: unity-license
          path: ~/.local/share/unity3d/Unity

      - name: Cache Unity Packages
        uses: actions/cache@v4
        with:
          path: Packages
          key: Packages-${{ inputs.testMode }}-${{ hashFiles('Packages/**', 'Packages/manifest.json') }}
          restore-keys: |
            Packages-${{ inputs.testMode }}-

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ inputs.testMode }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ inputs.testMode }}-

      - name: Print Unity Version & Selected Test Mode
        shell: bash
        run: |
          echo "🛠 Using Unity version: ${{ inputs.unityVersion }}"
          echo "🧪 Running tests: ${{ inputs.testMode }}"

      - name: Run ${{ inputs.testMode }} Tests
        id: run-tests
        timeout-minutes: ${{ inputs.timeoutMinutes }}
        continue-on-error: false
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          testMode: ${{ inputs.testMode }}

      - name: Upload ${{ inputs.testMode }} Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unity-${{ inputs.testMode }}-${{ github.sha }}
          path: ${{ steps.run-tests.outputs.artifactsPath }}
          retention-days: 7

      - name: Log Result Path
        run: |
          if [ -z "${{ steps.run-tests.outputs.artifactsPath }}" ]; then
            echo "⚠️ No test results found. Maybe test step was skipped or failed early."
          else
            echo "✅ Test results located at: ${{ steps.run-tests.outputs.artifactsPath }}"
          fi

      - name: Install xmllint (libxml2-utils)
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Extract Test Summary
        id: summary
        run: |
          XML=$(find "${{ steps.run-tests.outputs.artifactsPath }}" -name '*.xml' | head -n 1)

          if [[ -f "$XML" ]]; then
            TOTAL=$(xmllint --xpath 'string(/test-run/@total)' "$XML")
            PASSED=$(xmllint --xpath 'string(/test-run/@passed)' "$XML")
            RESULT=$(xmllint --xpath 'string(/test-run/@result)' "$XML")
            RAW_DURATION=$(xmllint --xpath 'string(/test-run/@duration)' "$XML")
            SECONDS=$(printf "%.0f" "$(echo "$RAW_DURATION" | awk '{print $1 * 1}')" )

            echo "total=$TOTAL" >> $GITHUB_OUTPUT
            echo "passed=$PASSED" >> $GITHUB_OUTPUT
            echo "result=$RESULT" >> $GITHUB_OUTPUT
            echo "durationSeconds=$SECONDS" >> $GITHUB_OUTPUT
          else
            echo "total=0" >> $GITHUB_OUTPUT
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "result=Skipped" >> $GITHUB_OUTPUT
            echo "durationSeconds=0" >> $GITHUB_OUTPUT
          fi
