name: 📚 Validate Deploy Targets

on:
  workflow_call:
    inputs:
      buildType:
        type: string
        required: true
      deployTargets:
        type: string
        required: true
    outputs:
      validTargets:
        value: ${{ jobs.validate.outputs.validTargets }}
      skipAnalysis:
        value: ${{ jobs.validate.outputs.skipAnalysis }}

jobs:
  validate:
    name: ✅ Validate Deploy Targets
    runs-on: ubuntu-latest
    outputs:
      validTargets: ${{ steps.filter.outputs.validTargets }}
      skipAnalysis: ${{ steps.early-check.outputs.skipRest }}

    steps:
      - name: 🔍 Inspect Input
        id: early-check
        run: |
          RAW_INPUT='${{ inputs.deployTargets }}'

          echo "🔍 Raw deployTargets input: $RAW_INPUT"

          # Validate JSON format
          if ! echo "$RAW_INPUT" | jq empty 2>/dev/null; then
            echo "❌ Invalid JSON in deployTargets input!"
            echo "validTargets=[]" >> $GITHUB_OUTPUT
            echo "skipRest=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check for empty array
          if [ "$(echo "$RAW_INPUT" | jq 'length')" -eq 0 ]; then
            echo "ℹ️ No deploy targets provided (empty array). Skipping validation."
            echo "validTargets=[]" >> $GITHUB_OUTPUT
            echo "skipRest=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Input is non-empty and valid JSON. Proceeding..."
          echo "skipRest=false" >> $GITHUB_OUTPUT

      - name: ⚙️ Validate Targets and Minimum Build Type
        id: filter
        if: steps.early-check.outputs.skipRest != 'true'
        run: |
          RAW_INPUT='${{ inputs.deployTargets }}'
          CONFIG_FILE=".github/config/deploy-targets.json"
          FALLBACK_URL="https://raw.githubusercontent.com/avalin/unity-ci-templates/main/.github/config/deploy-targets.json"
          BUILD_TYPE="${{ inputs.buildType }}"

          echo "🔍 Checking for local config file..."
          if [ -f "$CONFIG_FILE" ]; then
            echo "✅ Found local config file: $CONFIG_FILE"
          else
            echo "⚠️ Not found. Downloading from: $FALLBACK_URL"
            mkdir -p "$(dirname "$CONFIG_FILE")"
            curl -sSL "$FALLBACK_URL" -o "$CONFIG_FILE"
          fi

          # Define build type rank
          case "$BUILD_TYPE" in
            preview) BUILD_RANK=1 ;;
            release_candidate) BUILD_RANK=2 ;;
            release) BUILD_RANK=3 ;;
            *) echo "❌ Unknown build type: $BUILD_TYPE"; exit 1 ;;
          esac

          FINAL_VALID=()
          INVALID=()
          SKIPPED_MINIMUM=()

          for TARGET in $(echo "$RAW_INPUT" | jq -r '.[]'); do
            if jq -e --arg key "$TARGET" '.[$key]' "$CONFIG_FILE" >/dev/null; then
              MIN_TYPE=$(jq -r --arg key "$TARGET" '.[$key].minimumBuildType' "$CONFIG_FILE")

              case "$MIN_TYPE" in
                preview) MIN_RANK=1 ;;
                release_candidate) MIN_RANK=2 ;;
                release) MIN_RANK=3 ;;
                *) echo "❌ Unknown minimumBuildType for $TARGET: $MIN_TYPE"; exit 1 ;;
              esac

              if [ "$BUILD_RANK" -ge "$MIN_RANK" ]; then
                FINAL_VALID+=("$TARGET")
              else
                SKIPPED_MINIMUM+=("$TARGET (requires $MIN_TYPE)")
              fi
            else
              INVALID+=("$TARGET")
            fi
          done

          echo "✅ Final valid targets: ${FINAL_VALID[*]}"
          echo "⚠️ Invalid targets: ${INVALID[*]}"
          echo "⚠️ Skipped (minimum buildType not met): ${SKIPPED_MINIMUM[*]}"

          # Safely handle empty FINAL_VALID array
          if [ "${#FINAL_VALID[@]}" -eq 0 ]; then
            json='[]'
          else
            json=$(printf '%s\n' "${FINAL_VALID[@]}" | jq -R . | jq -s .)
          fi

          echo "validTargets<<EOF" >> $GITHUB_OUTPUT
          echo "$json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Export for summary step (join with | for safe splitting)
          echo "FINAL_VALID_TARGETS=${FINAL_VALID[*]}" >> $GITHUB_ENV
          echo "INVALID_TARGETS=${INVALID[*]}" >> $GITHUB_ENV
          echo "SKIPPED_MINIMUM=$(IFS='|'; echo "${SKIPPED_MINIMUM[*]}")" >> $GITHUB_ENV

      - name: 📋 Summary of Target Validation
        if: always()
        run: |
          FINAL_VALID_TARGETS="${FINAL_VALID_TARGETS:-}"
          INVALID_TARGETS="${INVALID_TARGETS:-}"
          SKIPPED_MINIMUM="${SKIPPED_MINIMUM:-}"

          # Convert skipped list back to array using | delimiter
          IFS='|' read -r -a SKIPPED_MINIMUM_ARRAY <<< "$SKIPPED_MINIMUM"

          echo ""
          echo "📋 Deploy Target Validation Summary"
          echo "────────────────────────────────────"
          if [ -n "$FINAL_VALID_TARGETS" ]; then
            echo "✅ Final Valid Targets:"
            for v in $FINAL_VALID_TARGETS; do echo "  - $v"; done
          else
            echo "ℹ️ No valid deploy targets remaining after validation."
          fi

          if [ -n "$INVALID_TARGETS" ]; then
            echo ""
            echo "⚠️ Invalid (Unknown) Targets:"
            for i in $INVALID_TARGETS; do echo "  - $i"; done
          fi

          if [ "${#SKIPPED_MINIMUM_ARRAY[@]}" -gt 0 ]; then
            echo ""
            echo "⚠️ Skipped (Minimum BuildType Not Met):"
            for s in "${SKIPPED_MINIMUM_ARRAY[@]}"; do
              echo "  - $s"
            done
          fi
          echo "────────────────────────────────────"