name: 🏷️ Version Tagger

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: preview | release_candidate | release"
        type: string
        required: true
      version:
        description: "Tag version (e.g., v1.2.3)"
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      buildType:
        type: string
        required: true

jobs:
  tag_resolver:
    name: 🏷️ Resolve & Create Tag
    if: ${{ inputs.buildType != 'preview' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag_existed: ${{ steps.check.outputs.exists }}

    steps:
      - name: 📁 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Helper Scripts
        run: chmod +x .github/scripts/tagging/*.sh

      - name: Check if Tag Exists
        id: check
        run: .github/scripts/tagging/check-tag-exists.sh "${{ inputs.version }}" "${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag if Missing
        if: ${{ steps.check.outputs.exists != 'true' }}
        id: create
        run: .github/scripts/tagging/create-tag.sh "${{ inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Output Version
        id: set_version
        run: |
          echo "version=${{ steps.create.outputs.version || inputs.version }}" >> "$GITHUB_OUTPUT"

  summarize_tagging:
    name: 📋 Summarize Tagging Info
    runs-on: ubuntu-latest
    needs: [tag_resolver]
    if: always()
    steps:
      - name: Print Summary
        run: |
          echo "### 🏷️ Tagging Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Type:** \`${{ inputs.buildType }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Requested Version:** \`${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ inputs.buildType }}" == 'preview' ]]; then
            echo "- ℹ️ Preview build detected — no tagging performed." >> $GITHUB_STEP_SUMMARY
          elif [[ '${{ needs.tag_resolver.outputs.tag_existed }}' == 'true' ]]; then
            echo "- ℹ️ Tag already existed — no new tag created." >> $GITHUB_STEP_SUMMARY
          else
            echo "- ✅ New tag created: \`${{ needs.tag_resolver.outputs.version || inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          fi
