name: 🏷️ Version Tagger

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version (e.g., v1.2.3)"
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  tag_resolver:
    name: 🏷️ Resolve & Create Tag
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Helper Scripts
        run: chmod +x .github/scripts/release/*.sh

      - name: Check if Tag Exists
        id: check
        run: .github/scripts/release/check-tag-exists.sh "${{ inputs.version }}" "${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag if Missing
        if: steps.check.outputs.exists != 'true'
        id: create
        run: .github/scripts/release/create-tag.sh "${{ inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Output Version
        id: set_version
        run: |
          echo "version=${{ steps.create.outputs.version || inputs.version }}" >> "$GITHUB_OUTPUT"

      - name: 📋 Summarize Tagging Info
        if: always()
        run: |
          echo "### 🏷️ Tagging Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Requested Version:** \`${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.check.outputs.exists }}" == 'true' ]]; then
            echo "- ℹ️ Tag already existed — no new tag created." >> $GITHUB_STEP_SUMMARY
          else
            echo "- ✅ New tag created: \`${{ steps.create.outputs.version || inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          fi